auto: true

markdown: rdiscount
highlighter: true
paginate: 8
permalink: /:title

title: boqodo
url: http://boqodo.github.io/
feed: /atom.xml
author_info: <a href="http://boqodo.github.io/">boqodo</a>
